name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare Docker buildx
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --use --name builder
        docker buildx ls
    - name: Build images
      run: |
        docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le -t cpp-cmake:test .
