name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare Docker buildx
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --use --name builder
        docker buildx ls
    - name: Build image linux/amd64
      run: |
        docker buildx build --platform linux/amd64 -t cpp-cmake:test .
    - name: Build image linux/arm/v7
      run: |
        docker buildx build --platform linux/arm/v7 -t cpp-cmake:test .
    - name: Build image linux/arm64
      run: |
        docker buildx build --platform linux/arm64 -t cpp-cmake:test .
    - name: Build image linux/ppc64le
      run: |
        docker buildx build --platform linux/ppc64le -t cpp-cmake:test .
