name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare Docker buildx platforms
      run: docker run --privileged --rm tonistiigi/binfmt --install all
    - name: Show Docker buildx platforms
      run: docker buildx ls
