name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-platform: [linux/amd64, linux/arm/v7, linux/arm64, linux/ppc64le]

    steps:
    - uses: actions/checkout@v2
    
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build image
      run: |
        docker buildx build --push --platform linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le -t cpp-cmake:latest .
